github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # configure whether Gitpod registers itself as a status check to pull requests
    addCheck: false

image:
  file: .gitpod.Dockerfile

tasks:
  - name: start
    command: confluent local services start && gp sync-done start
  - name: datagen
    command: |
      gp sync-await start
      
      curl -i -X PUT -H "Content-Type:application/json" \
        http://localhost:8083/connectors/users/config \
        -d '{
           "connector.class" : "io.confluent.kafka.connect.datagen.DatagenConnector",
           "kafka.topic" : "stockapp.users",
           "quickstart" : "Users_",
           "max.interval" : "8000",
           "tasks.max" : "1"
          }'
          
      curl -i -X PUT -H "Content-Type:application/json" \
        http://localhost:8083/connectors/trades/config \
        -d '{
           "connector.class" : "io.confluent.kafka.connect.datagen.DatagenConnector",
           "kafka.topic" : "stockapp.trades",
           "quickstart" : "Stock_Trades",
           "max.interval" : "8000",
           "tasks.max" : "1" 
          }'

ports:
  # zookeeper
  - port: 2181
    onOpen: ignore
    
  # Confluent Server (broker)
  - port: 9092
    onOpen: ignore
    
  # Confluent Server (REST)
  - port: 8090
    onOpen: ignore
    
  # Schema Registry
  - port: 8081
    onOpen: ignore
  - port: 8082
    onOpen: ignore
    
  # Kafka Connect
  - port: 8083
    onOpen: ignore
    
  # ksqlDB
  - port: 8088
    onOpen: ignore
    
  # Confluent Control Center
  - port: 9021
    onOpen: notify
    visibility: public
